version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Ruby: 3, 3.1, 3.0, 2, 2.7, 2.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "${VARIANT:-3-bullseye}"
        # Optional Node.js version to install
        NODE_VERSION: "none"
        APP_NAME: ${APP_NAME:-myapp}

    volumes:
      - ..:/${APP_NAME:-myapp}:cached
      - bundle:/${APP_NAME:-myapp}/vendor/bundle

    env_file:
      - .env

    tty: true
    stdin_open: true

volumes:
  bundle: null
